version: "3"
services:
  database:
    container_name: postgresql_giyu 
    image: "postgres"
    env_file:
      - ./config/database.env
    ports:
      - "12321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./config/create_schemas.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - database-network

  pgadmin:
    container_name: pgadmin_giyu
    image: dpage/pgadmin4
    env_file:
      - ./config/pgadmin.env
    ports:
      - "12123:80"
    depends_on:
      - database
    networks:
      - database-network

volumes: 
  pgdata:

networks:
  database-network:
    driver: bridge
